[theme]
name = "native"

[icons]
name = "awesome5"

[[block]]
block = "weather"
format = " {weather}{temp}C"
autolocate = false
service = { name = "openweathermap", api_key = "172d9bcd52349d130e5b0c5bf4adf7f6", city_id = "2751283", units = "metric" }

[[block]]
block = "sound"
on_click = "pavucontrol"
step_width = 1

[[block]]
block = "bluetooth"
mac = "00:1B:66:BC:44:DC"
format = "Momentum TW2"
on_click = "blueberry"

[[block]]
block = "net"
device = "wlan0"
format = " {ssid}"
interval = 5
on_click = "foot -e iwctl"

[[block]]
block = "battery"
allow_missing = true
hide_missing = true
interval = 30
format = " {percentage}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "custom"
command = "echo \uf011"
on_click = "$HOME/.config/i3status-rust/scripts/powermenu.sh"
interval = "once"
