[theme]
theme = "native"

[icons]
icons = "awesome5"

[[block]]
block = "weather"
[block.service]
name = "openweathermap"
api_key = "172d9bcd52349d130e5b0c5bf4adf7f6"
city_id = "2751283"
units = "metric"

[[block]]
block = "sound"
step_width = 1
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "bluetooth"
mac = "00:1B:66:BC:44:DC"
format = " $icon Earbuds "
disconnected_format = " $icon "

[[block]]
block = "net"
device = "wlan0"
format = " $icon $ip "
missing_format = " $icon "

[[block]]
block = "net"
device = "enp2s0f0"
format = " $icon $ip "
missing_format = ""

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "custom"
command = "echo \uf011"
interval = "once"
[[block.click]]
button = "left"
cmd = "$HOME/.config/i3status-rust/scripts/powermenu.sh"

[[block]]
block = "battery"
interval = 60
